src/lang/tokenizer/test/tokenizer.test.o: src/convert/fd/source.h
src/lang/tokenizer/test/tokenizer.test.o: src/convert/source.h
src/lang/tokenizer/test/tokenizer.test.o: src/convert/status.h
src/lang/tokenizer/test/tokenizer.test.o: src/lang/error/error.h
src/lang/tokenizer/test/tokenizer.test.o: src/lang/tokenizer/tokenizer.h
src/lang/tokenizer/test/tokenizer.test.o: src/log/log.h
src/lang/tokenizer/test/tokenizer.test.o: src/range/def.h
src/lang/tokenizer/test/tokenizer.test.o: src/window/alloc.h
src/lang/tokenizer/test/tokenizer.test.o: src/window/def.h
src/lang/tokenizer/tokenizer.o: src/convert/source.h
src/lang/tokenizer/tokenizer.o: src/convert/status.h
src/lang/tokenizer/tokenizer.o: src/lang/error/error.h
src/lang/tokenizer/tokenizer.o: src/lang/tokenizer/tokenizer.h
src/lang/tokenizer/tokenizer.o: src/log/log.h
src/lang/tokenizer/tokenizer.o: src/range/def.h
src/lang/tokenizer/tokenizer.o: src/window/def.h
